name: Docker Build and Archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set script permissions
        run: chmod +x ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker command
        run: docker run -v ${PWD}:/app ghcr.io/zylquinal/crosscompile-env:master /app/build.sh

      - name: Archive dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist-archive
          path: dist/

      - name: Checksums & Archive
        run: |
          sudo chown -R $(whoami) ./dist
          cd dist
          find . -type f ! -name ".*" -exec sha256sum {} \; > checksums.txt
          zip -r archive.zip *

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          body_path: dist/checksums.txt
          files: ./dist/archive.zip